# Generated by Django 6.0.6 on 2026-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('original_external_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('incident_date', models.DateTimeField()),
                ('declared_urgency', models.IntegerField()),
                ('vulnerability_victim', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('analyzed', 'Analyzed'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='imported', max_length=20)),
                ('received_at', models.DateTimeField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
