# Generated by Django 6.0.6 on 2026-06-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='raw_payload',
            field=models.JSONField(default=dict),
        ),
    ]
