# Generated by Django 6.0.6 on 2026-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CRITICAL_COMPLAINT', 'Critical Complaint'), ('PRIORITY_REVIEW_REQUIRED', 'Priority Review Required'), ('SYNC_COMPLETED', 'Sync Completed'), ('SYNC_FAILED', 'Sync Failed')], default='CRITICAL_COMPLAINT', max_length=50),
        ),
    ]
