# Generated by Django 6.0.6 on 2026-06-10 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_type', models.CharField(choices=[('COMPLAINT_IMPORTED', 'Complaint Imported'), ('COMPLAINT_VIEWED', 'Complaint Viewed'), ('PRIORITY_ASSESSED', 'Priority Assessed'), ('PRIORITY_CONFIRMED', 'Priority Confirmed'), ('PRIORITY_OVERRIDDEN', 'Priority Overridden'), ('SYNC_STARTED', 'Sync Started'), ('SYNC_FAILED', 'Sync Failed'), ('USER_LOGGED_IN', 'User Logged In'), ('USER_LOGGED_OUT', 'User Logged Out')], max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
