# Generated by Django 6.0.6 on 2026-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='action',
            field=models.CharField(choices=[('COMPLAINT_IMPORTED', 'Complaint Imported'), ('COMPLAINT_VIEWED', 'Complaint Viewed'), ('PRIORITY_ASSESSED', 'Priority Assessed'), ('PRIORITY_CONFIRMED', 'Priority Confirmed'), ('PRIORITY_OVERRIDDEN', 'Priority Overridden'), ('SYNC_STARTED', 'Sync Started'), ('SYNC_FAILED', 'Sync Failed'), ('USER_LOGGED_IN', 'User Logged In'), ('USER_LOGGED_OUT', 'User Logged Out')], max_length=255),
        ),
        migrations.AlterField(
            model_name='audit',
            name='target_type',
            field=models.CharField(max_length=255),
        ),
    ]
