# Generated by Django 6.0.6 on 2026-06-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('summary', models.TextField()),
                ('explanation', models.JSONField(default=dict)),
                ('recommended_actions', models.JSONField(default=list)),
                ('detected_risks', models.JSONField(default=list)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
            ],
        ),
    ]
